## Title of the blog
title: Minimal test blog

subtitle: based on the Humane theme

## Name of the blog author
author: John Smith

## Name of used blog theme. This uses the default bundled theme called 'humane'.
theme: humane