## Title of the blog
title: Minimal test blog

## Subtitle of the blog (optional)
subtitle: based on the Humane theme

## Name of used blog theme. This uses the default bundled theme called 'humane'
theme: humane

## Blog copyright info (optional)
copyright: Copyright © 2016-2017 John Smith

## Blog authors (at least one author per blog must be defined)
authors:

  ## Author with unique nickname 'john.smith'
  john.smith:

    ## Real name of the author
    name: John Smith

    ## Path to the author avatar/portrait image (optional)
    avatar: images/avatars/john-smith.jpg

    ## Short biography of the author (optional)
    biography: >
      Here belongs short author biography. Some themes may provide support for some formatting
      options, for example the *Humane* theme allows to format biography using the *Markdown*
      format.