## Title of the blog
title: Minimal test blog

## Name of the blog author
author: John Smith

## (Optional) Name of used blog theme. If not specified, default bundled theme 'humane' is used.
theme: humane